name: First CI

on:
  push:
    branches:
    - main

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

  install-deps:
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

  testes:
    - name: Run tests
      run: npm run test:headless

  build:
    - name: Build
      run: npm run build:prod
