name: Staging

on:
  push:
    branches:
    - develop

jobs:
  env:
    - name: Install dependencies
      run: echo ${{  secrets.TEST  }}
  test:
    needs: checkout
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./github-actions-poc
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: Install dependencies
      run: npm install
    - name: Run tests
      run: npm run test
  build:
    needs: checkout
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./github-actions-poc
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: Install dependencies
      run: npm install
    - name: Build
      run: npm run build
